### ISSUE TITLE
Service error when receiving request from client 

### ISSUE THREAD

**Issue by m-hari16** [Cexup-Team/Medical-Record-Rendering#6]
endpoint: {base_url}/render/electrocardiogram?id={id}
![WhatsApp Image 2022-09-24 at 1 44 52 PM](https://user-images.githubusercontent.com/54405674/192086143-221faf35-df3d-4bfb-98e9-dc7eb9d9bc5f.jpeg)

**Comment by triandamai** [comment]
this happen because we sen response twice :-(

```js
res.writeHead(200,"response")
res.send("response")
```

**Comment by m-hari16** [comment]
The service has been deployed and running normally.
